- versioninfo.json
> Updated versioninfo.json

- modules/azure-front-door/.gitignore
- modules/node-app-service/.gitignore
- modules/node-app-service/README.md
- modules/node-app-service/locals.tf
- modules/node-app-service/secrets.tf
- modules/node-function-app/.gitignore
* added docker registry password to key vault
* added .gitignore file to modules
* added .gitignore file to modules
---------
> added docker registry password to key vault (#17)

- .github/pull_request_template.md
creating the md file for the pr template
Should there be any other questions included?
> creating a pull template

- .github/pull_request_template.md
> testing the pr template with dummy text

- modules/azure-front-door/.gitignore
- modules/node-app-service/.gitignore
- modules/node-function-app/.gitignore
> hashed out fdp ruleset and rules

- release-automation/Tag-Repo.ps1
> updated tag-repo script

- azure-pipelines/steps/release-automation.yaml
> Alex release

- azure-pipelines/steps/release-automation.yaml
> Release testing

- azure-pipelines/steps/release-automation.yaml
Testing updating the release-automation.yaml to only trigger on main to try resolve pipeline error
- [DEV-79](fix/dev-79-release-automation-pipelone)
> update release-automation.yaml to trigger on main

- azure-pipelines/steps/release-automation.yaml
Reverts Planning-Inspectorate/infrastructure-modules#33
> Revert "update release-automation.yaml to trigger on main"

- azure-pipelines/steps/release-automation.yaml
- release-automation/Tag-Repo.ps1
> adding in outputs to check script breakdown

- modules/ci-modules/node-app-service/main.tf
- modules/ci-modules/node-app-service/variable.tf
- modules/node-app-service/README.md
- modules/node-app-service/variables.tf
Removed the variables for secrets and key vault uri which were added previously and are not needed in the module
DEV-80
> ci-modules node-app-service

- .tflint.hcl
upgraded tflint from 0.19.0 to 0.25.1
DEV-80
> upgraded tflint from 0.19.0 to 0.25.1

- modules/node-app-service/main.tf
added public network access enabled as a variable so the environments can inherit it. This will allow us to add it as true to the dev environments while it can inherit the false flag from the module on test and prod.
DEV-81
> added a variable for public network access enabled

- modules/ci-modules/node-function-app/main.tf
- modules/ci-modules/node-function-app/variables.tf
- modules/node-function-app/README.md
- modules/node-function-app/data.tf
- modules/node-function-app/main.tf
- modules/node-function-app/variables.tf
Added Key Vault Access Policy for node-function-app
Updated node function app module and added a ci module test folder and files
DEV-81
> Added Key Vault Access Policy and a CI module test folder and files

- modules/node-function-app/README.md
- modules/node-function-app/main.tf
- modules/node-function-app/variables.tf
Update private endpoint argument for node-function-app
DEV-81
> Update private endpoint argument for node-function-app

- modules/node-function-app/variables.tf
Upgraded default node version for function app module to 18
DEV-86
> Upgraded default node version for function app module to 18

- modules/node-function-app/README.md
- modules/node-function-app/variables.tf
updated README.md for function app module
DEV-86
> updated README.md for function app module

- modules/node-app-service/main.tf
- modules/node-app-service/variables.tf
- [BOAS-481](https://pins-ds.atlassian.net/browse/BOAS-481)
- This is to set up health checks on the back office API.
> Add optional health check path parameter to node-app-service

- modules/azure-front-door/provider.tf
- modules/azure-front-door/test/main.tf
- modules/azure-front-door/test/provider.tf
- modules/azure-front-door/test/variable.tf
Update provider files to enable integration with infrastructure environments
DEV-90
> Update provider files to enable integration with infrastructure environments

- modules/azure-front-door/test/variable.tf
- modules/azure-front-door/variables.tf
> updated variables

- release-automation/Tag-Repo.ps1
Attempt to fix Tag-Repo script.
> ci: fix Tag-Repo script to find last tag

- modules/node-app-service/outputs.tf
https://pins-ds.atlassian.net/browse/AAPD-1045
Output resource id of web app
> feat(appeals-fo): add resource id to web app outputs

- modules/node-app-service/monitoring.tf
- modules/node-app-service/test/main.tf
- modules/node-app-service/test/variable.tf
- modules/node-app-service/variables.tf
- modules/node-function-app/monitoring.tf
- modules/node-function-app/test/main.tf
- modules/node-function-app/test/variables.tf
- modules/node-function-app/variables.tf
https://pins-ds.atlassian.net/browse/DEV-95
- add more action groups for alerts
> feat: extra alert action groups

- modules/node-app-service/monitoring.tf
- modules/node-function-app/monitoring.tf
> fix: set severity level for 5xx alerts

- azure-pipelines/steps/install-checkov.yaml
- modules/azure-front-door/region.tf
- modules/node-app-service/README.md
- modules/node-app-service/main.tf
- modules/node-function-app/main.tf
- DEV-150
- Updated Checkov version for the modules to 3.2.31.
- Added some skips for Private endpoints for now as TODO otherwise we will need to add private endpoints to all web apps and function apps immediately which as a result may block releases.
> Updated Checkov version for the modules to 3.2.31

- modules/node-function-app/README.md
- modules/node-function-app/locals.tf
- modules/node-function-app/main.tf
- modules/node-function-app/variables.tf
> feat: support existing app insights instance for function apps

- modules/node-function-app/README.md
- modules/node-function-app/locals.tf
- modules/node-function-app/main.tf
- modules/node-function-app/variables.tf
An instance can still be passed in.
> feat: remove app insights instance from function module

- modules/azure-front-door/waf-policy.tf
- dev 243
- implementing waf policy rate limit on azure front door premium
> implementing waf rate limit for azure front door premium

- .pre-commit-config.yaml
- README.md
- modules/azure-front-door/provider.tf
- modules/azure-front-door/region.tf
- modules/node-app-service/locals.tf
- modules/node-app-service/main.tf
- modules/node-app-service/monitoring.tf
- modules/node-app-service/provider.tf
- modules/node-app-service/variables.tf
- modules/node-function-app/monitoring.tf
- modules/node-function-app/provider.tf
Have not added this required change in yet as could be a breaking change. Perhaps merge this PR in as it's smaller and then raise another one?
https://registry.terraform.io/providers/hashicorp/azurerm/4.5.0/docs/resources/linux_web_app
NOTE:
docker_registry_url, docker_registry_username, and docker_registry_password replace the use of the app_settings values of DOCKER_REGISTRY_SERVER_URL, DOCKER_REGISTRY_SERVER_USERNAME and DOCKER_REGISTRY_SERVER_PASSWORD respectively, these values will be managed by the provider and should not be specified in the app_settings map.
> upgrade to azurerm v4

- modules/node-app-service/main.tf
- modules/node-app-service/variables.tf
> adding health check

- modules/node-app-service/main.tf
> fix: set ip restrictions for staging slot

- modules/node-app-service/locals.tf
> fix(tooling): updating the CI tag to false

- modules/node-app-service/main.tf
- modules/node-app-service/variables.tf
Implementing Azure authentication to enable only PINS Id's to access services 
> task(infrastructure): adding Easy Auth setting to web app service

- .tflint.hcl
- modules/azure-front-door/provider.tf
> chore: upgrading-terraform

- modules/node-app-service/variables.tf
> task: add value to health check

- modules/node-app-service/main.tf
- modules/node-app-service/variables.tf
Adding this change to Enable  network access and Deny all access except Front Door for Web project and  public access completely disabled for API's
ticket: https://pins-ds.atlassian.net/browse/DEV-308
> fix(infrastructure): network slot access for web apps and api

- modules/node-app-service/provider.tf
- modules/node-function-app/provider.tf
updating terraform required condition to include latest version 
> task(infrastructure): updating terraform required condition

- modules/node-app-service/main.tf
- modules/node-app-service/variables.tf
Adding excluded path variable for authentication.
this would be a list of context paths that are exempted from authentication 
> fix(infrastructure): adding exclude paths for authentication

- modules/node-app-service/main.tf
- modules/node-app-service/variables.tf
updating allowed applications data type to list (string) to add more applications
> fix(infrastructure): modifying data type for allowed application in authentication

- modules/node-app-service/monitoring.tf
Adjust alert rules for front office:
-increase the severity level and lower threshold of slow response alert
-increase threshold fof the 500 alert
> feat(node-app-service): adjust alert rules

- modules/node-app-service/main.tf
- modules/node-app-service/variables.tf
Revert the data type of allowed applications to string as it is no longer needed as list by any projects
> Revert "fix(infrastructure): modifying data type for allowed application in authentication"

- modules/node-app-service/variables.tf
Setting excluded_path as optional in easy auth configuration 
> fix(infrastructure): making excluded paths optional

- modules/node-function-app/locals.tf
> fix(node-function-app): set Host.Aggregator and Host.Results log levels correctly
